In [1]:
import pandas as pd
import numpy as np

In [2]:
inputs=pd.read_csv('Diabetes_XTrain.csv')
targets=pd.read_csv('Diabetes_YTrain.csv')

In [3]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

In [4]:
train_test_split(inputs, targets)

[     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 42            11      127            106              0        0  39.0   
 120            3       87             60             18        0  21.8   
 280            6       99             60             19       54  26.9   
 264            0       84             64             22       66  35.8   
 214            1      139             46             19       83  28.7   
 ..           ...      ...            ...            ...      ...   ...   
 389            4      146             92              0        0  31.2   
 35             0      120             74             18       63  30.5   
 489            4      111             72             47      207  37.1   
 115            4       90              0              0        0  28.0   
 510            0      119             64             18       92  34.9   
 
      DiabetesPedigreeFunction  Age  
 42                      0.190   51  
 120                  

In [17]:
x_train, x_test, y_train, y_test = train_test_split(inputs, targets, #train_size = 0.85, 
                                                                            test_size = 0.15)

In [18]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(489, 8) (489, 1)


In [19]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(87, 8) (87, 1)


In [20]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

# create a logistic regression object
reg = LogisticRegression()

In [21]:
# fit our train inputs
# this is training part of the machine learning
reg.fit(x_train,y_train)

/Users/tushartinna/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/tushartinna/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7811860940695297

In [23]:
# get the intercept (bias) of our model
reg.intercept_

array([-8.43161128])

In [24]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 1.12692211e-01,  3.67635344e-02, -1.53091077e-02,
        -3.25106954e-03, -6.26885200e-04,  9.88594650e-02,
         1.17293477e+00,  6.12092363e-03]])

In [25]:
# check what were the names of our columns
inputs.columns.values
# save the names of the columns in an ad-hoc variable
feature_name = inputs.columns.values

In [26]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0               Pregnancies     0.112692
1                   Glucose     0.036764
2             BloodPressure    -0.015309
3             SkinThickness    -0.003251
4                   Insulin    -0.000627
5                       BMI     0.098859
6  DiabetesPedigreeFunction     1.172935
7                       Age     0.006121

In [27]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table.sort_values('Odds_ratio', ascending=False)
summary_table

Feature name  Coefficient  Odds_ratio
0               Pregnancies     0.112692    1.119287
1                   Glucose     0.036764    1.037448
2             BloodPressure    -0.015309    0.984807
3             SkinThickness    -0.003251    0.996754
4                   Insulin    -0.000627    0.999373
5                       BMI     0.098859    1.103911
6  DiabetesPedigreeFunction     1.172935    3.231462
7                       Age     0.006121    1.006140

In [28]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.7816091954022989

In [29]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.93005005, 0.06994995],
       [0.12227912, 0.87772088],
       [0.87311128, 0.12688872],
       [0.85626041, 0.14373959],
       [0.95524343, 0.04475657],
       [0.10437645, 0.89562355],
       [0.26839099, 0.73160901],
       [0.52406768, 0.47593232],
       [0.81513762, 0.18486238],
       [0.51487929, 0.48512071],
       [0.79618486, 0.20381514],
       [0.99397162, 0.00602838],
       [0.26026425, 0.73973575],
       [0.93513696, 0.06486304],
       [0.1600188 , 0.8399812 ],
       [0.94924796, 0.05075204],
       [0.92478098, 0.07521902],
       [0.36449817, 0.63550183],
       [0.86037706, 0.13962294],
       [0.80545325, 0.19454675],
       [0.52153449, 0.47846551],
       [0.84720058, 0.15279942],
       [0.87360255, 0.12639745],
       [0.67070425, 0.32929575],
       [0.23156005, 0.76843995],
       [0.0465551 , 0.9534449 ],
       [0.74716967, 0.25283033],
       [0.62878718, 0.37121282],
       [0.64043035, 0.35956965],
       [0.92785089, 0.07214911],
       [0.

In [30]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.06994995, 0.87772088, 0.12688872, 0.14373959, 0.04475657,
       0.89562355, 0.73160901, 0.47593232, 0.18486238, 0.48512071,
       0.20381514, 0.00602838, 0.73973575, 0.06486304, 0.8399812 ,
       0.05075204, 0.07521902, 0.63550183, 0.13962294, 0.19454675,
       0.47846551, 0.15279942, 0.12639745, 0.32929575, 0.76843995,
       0.9534449 , 0.25283033, 0.37121282, 0.35956965, 0.07214911,
       0.23730301, 0.10314466, 0.22777479, 0.24110523, 0.6847871 ,
       0.19227824, 0.14752494, 0.03696078, 0.18861329, 0.28899308,
       0.05366985, 0.72667276, 0.17604296, 0.85184132, 0.59766873,
       0.74224856, 0.07564157, 0.97597961, 0.09329212, 0.04802262,
       0.81736949, 0.73453941, 0.91285185, 0.52238398, 0.06936317,
       0.07197448, 0.98442511, 0.91160148, 0.72109276, 0.25349959,
       0.28792374, 0.25660707, 0.04347207, 0.15457721, 0.42580964,
       0.48780746, 0.71184062, 0.40539495, 0.22039535, 0.26008888,
       0.08444772, 0.02109958, 0.1303392 , 0.65008846, 0.26741

In [31]:
# import the relevant module
import pickle

In [33]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)